spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${spring.datasource.name}?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
    name: autoCreateData
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
