spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${spring.datasource.name}?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
    name: autoCreateData
  redis:
    host: localhost
    port: 6379
    password: redisPassword
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-wait: -1
        max-active: 8
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

#logging: 可以看到很多日志
# level:
#    root: debug
